"""Initial migration: Application and APIKey tables

Revision ID: 8cd48ec3d429
Revises: 
Create Date: 2025-11-12 15:26:06.702197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd48ec3d429'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_keys_application_id', table_name='api_keys')
    op.drop_index('idx_api_keys_is_active', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_application_id'), 'api_keys', ['application_id'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.drop_constraint('applications_slug_key', 'applications', type_='unique')
    op.drop_index('idx_applications_slug', table_name='applications')
    op.drop_index('idx_applications_status', table_name='applications')
    op.create_index(op.f('ix_applications_slug'), 'applications', ['slug'], unique=True)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_slug'), table_name='applications')
    op.create_index('idx_applications_status', 'applications', ['status'], unique=False)
    op.create_index('idx_applications_slug', 'applications', ['slug'], unique=False)
    op.create_unique_constraint('applications_slug_key', 'applications', ['slug'])
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_application_id'), table_name='api_keys')
    op.create_index('idx_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_api_keys_application_id', 'api_keys', ['application_id'], unique=False)
    # ### end Alembic commands ###
